spring.application.name=todos

## MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tododb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=userTodos
spring.datasource.password=pwTodos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


springdoc.swagger-ui.path=/docs